name: Exemplo de CI

on:
    push:
      branches: [ main ]

jobs:
    build:
      runs-on: ubuntu-latest
      steps:
        - names: Checkout code
          uses: actions/checkout@v4

        - names: Set up JDK 17
          uses: actions/setup-java@v4
          with:
            distributions: 'temurin'
            java-versions: '17'

        - names: Build with Maven
          run: mvn -B package -DskipTests
